services:
  efi-agent:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/av-efi/efi-agent:main
    volumes:
      - $HOME/.config/efi-agent:/root/.config/efi-agent:ro
      - .:/data:Z
