services:
  efi-agent:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/av-efi/efi-agent:latest
    volumes:
      - $HOME/.config/efi_agent:/root/.config/efi_agent:ro
      - .:/data:Z
